data(iris)
cat("Dimension of the dataset:", dim(iris), "\n")
str(iris)
summary(iris)
cat("Standard Deviation of all features:\n")
sapply(iris[, 1:4], sd)
cat("\n")
by_species <- by(iris[, 1:4], iris$Species, colMeans)
cat("Mean by species:\n")
print(by_species)
cat("Standard Deviation by species:\n")
by(iris[, 1:4], iris$Species, function(x) apply(x, 2, sd))
cat("\n")
quantile(iris$Sepal.Length)
quantile(iris$Sepal.Width)
iris$Sepal.Length.Cate <- cut(iris$Sepal.Length, breaks = quantile(iris$Sepal.Length), labels = FALSE)
iris1 <- iris
aggregate(iris1[, 1:4], by = list(Species = iris1$Species, Sepal.Length.Cate = iris1$Sepal.Length.Cate), FUN = mean)
aggregate(iris1[, 1:4], by = list(Species = iris1$Species, Sepal.Length.Cate = iris1$Sepal.Length.Cate), FUN = function(x) mean(x, na.rm = TRUE))
library(dplyr)
pivot_table <- iris1 %>%
  group_by(Species, Sepal.Length.Cate) %>%
  summarise_all(mean)
print(pivot_table)